# Generated by Django 3.2.25 on 2024-09-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel3',
            new_name='MyModel',
        ),
    ]
